name: 'Workspace gitconfig action'
description: 'Provide a workspace scope gitconfig'
author: 'srz-zumix'

inputs:
  configs:
    description: 'git .config file format text'
  workspace:
    description: 'workspace path'
    default: ${{ github.workspace }}

outputs:
  config_path:
    description: 'workspace gitconfig file path'

runs:
  using: node24
  main: dist/main/index.js
  post: dist/post/index.js

branding:
  icon: 'edit'
  color: 'gray-dark'
