name: 'Workspace gitconfig action'
description: 'Provide a workspace scope gitconfig'
author: 'srz-zumix'

branding:
  icon: 'edit'
  color: 'gray-dark'

inputs:
  configs:
    description: 'git .config file format text'

outputs:
  config_path:
    description: 'workspace gitconfig file path'

runs:
  using: node16
  main: dist/main/index.js
