name: Update Semver
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
  release:
    types: [published]
  workflow_dispatch:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  update-semver:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: haya14busa/action-update-semver@22a3666f9309f0d72ab0ea6c49b7a8019c1eab38 # v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.tag || '' }}
